<a href="https://colab.research.google.com/github/Rudrabhatt007/Data_Science/blob/main/numpy_tricks(15).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 5, 88, 80, 90],
       [32, 41, 22, 68],
       [ 7, 25, 56,  4],
       [91, 11, 92, 71],
       [ 8,  7, 88, 51],
       [87, 85, 43, 45]])

In [3]:
np.sort(a)

array([ 5, 23, 23, 24, 27, 38, 41, 54, 60, 67, 71, 78, 82, 87, 96])

In [5]:
np.sort(b,axis=0)

array([[ 5,  7, 22,  4],
       [ 7, 11, 43, 45],
       [ 8, 25, 56, 51],
       [32, 41, 80, 68],
       [87, 85, 88, 71],
       [91, 88, 92, 90]])

In [7]:
np.sort(a)[::-1]#desending

array([96, 87, 82, 78, 71, 67, 60, 54, 41, 38, 27, 24, 23, 23,  5])

In [8]:
np.sort(b,axis=0)

array([[ 5,  7, 22,  4],
       [ 7, 11, 43, 45],
       [ 8, 25, 56, 51],
       [32, 41, 80, 68],
       [87, 85, 88, 71],
       [91, 88, 92, 90]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
np.append(a,200)

array([ 78,  24,  82,  87,  67,   5,  23,  71,  38,  60,  54,  41,  96,
        23,  27, 200])

In [10]:
b

array([[ 5, 88, 80, 90],
       [32, 41, 22, 68],
       [ 7, 25, 56,  4],
       [91, 11, 92, 71],
       [ 8,  7, 88, 51],
       [87, 85, 43, 45]])

In [13]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 5., 88., 80., 90.,  1.],
       [32., 41., 22., 68.,  1.],
       [ 7., 25., 56.,  4.,  1.],
       [91., 11., 92., 71.,  1.],
       [ 8.,  7., 88., 51.,  1.],
       [87., 85., 43., 45.,  1.]])

In [14]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[ 5.        , 88.        , 80.        , 90.        ,  0.15221014],
       [32.        , 41.        , 22.        , 68.        ,  0.24900735],
       [ 7.        , 25.        , 56.        ,  4.        ,  0.33308476],
       [91.        , 11.        , 92.        , 71.        ,  0.69704833],
       [ 8.        ,  7.        , 88.        , 51.        ,  0.78241612],
       [87.        , 85.        , 43.        , 45.        ,  0.93510869]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [15]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [16]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [18]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [19]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [20]:
# code
a.shape

(15,)

In [21]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [22]:
np.expand_dims(a,axis=1)

array([[78],
       [24],
       [82],
       [87],
       [67],
       [ 5],
       [23],
       [71],
       [38],
       [60],
       [54],
       [41],
       [96],
       [23],
       [27]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [23]:
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [24]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  4,  7,  9, 10, 12]),)

In [27]:
# replace all values > 50 with 0
np.where(a>50,0,a)#(condition,replace value)

array([ 0, 24,  0,  0,  0,  5, 23,  0, 38,  0,  0, 41,  0, 23, 27])

In [25]:
np.where(a%2 == 0,0,a)

array([ 0,  0,  0, 87, 67,  5, 23, 71,  0,  0,  0, 41,  0, 23, 27])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [28]:
# code
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [29]:
np.argmax(a)

12

In [30]:
b

array([[ 5, 88, 80, 90],
       [32, 41, 22, 68],
       [ 7, 25, 56,  4],
       [91, 11, 92, 71],
       [ 8,  7, 88, 51],
       [87, 85, 43, 45]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [31]:
np.argmax(b,axis=1)

array([3, 3, 2, 2, 2, 0])

In [32]:
# np.argmin
np.argmin(a)

5

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [33]:
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [34]:
np.cumsum(a)

array([ 78, 102, 184, 271, 338, 343, 366, 437, 475, 535, 589, 630, 726,
       749, 776])

In [35]:
b

array([[ 5, 88, 80, 90],
       [32, 41, 22, 68],
       [ 7, 25, 56,  4],
       [91, 11, 92, 71],
       [ 8,  7, 88, 51],
       [87, 85, 43, 45]])

In [36]:
np.cumsum(b,axis=1)

array([[  5,  93, 173, 263],
       [ 32,  73,  95, 163],
       [  7,  32,  88,  92],
       [ 91, 102, 194, 265],
       [  8,  15, 103, 154],
       [ 87, 172, 215, 260]])

In [37]:
np.cumsum(b)

array([   5,   93,  173,  263,  295,  336,  358,  426,  433,  458,  514,
        518,  609,  620,  712,  783,  791,  798,  886,  937, 1024, 1109,
       1152, 1197])

In [38]:
# np.cumprod
np.cumprod(a)

array([                  78,                 1872,               153504,
                   13354848,            894774816,           4473874080,
               102899103840,        7305836372640,      277621782160320,
          16657306929619200,   899494574199436800,   -14210605242194432,
       -1364218103250665472,  5516471772653797376,  1370785271976116224])

In [39]:
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [40]:
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [41]:
np.percentile(a,50)

54.0

In [42]:
np.median(a)

54.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [43]:
# code
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [44]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [45]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [46]:
# code
a


array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [47]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [48]:
# code
a

array([78, 24, 82, 87, 67,  5, 23, 71, 38, 60, 54, 41, 96, 23, 27])

In [49]:
np.flip(a)

array([27, 23, 96, 41, 54, 60, 38, 71, 23,  5, 67, 87, 82, 24, 78])

In [50]:
b

array([[ 5, 88, 80, 90],
       [32, 41, 22, 68],
       [ 7, 25, 56,  4],
       [91, 11, 92, 71],
       [ 8,  7, 88, 51],
       [87, 85, 43, 45]])

In [51]:
np.flip(b,axis=1)

array([[90, 80, 88,  5],
       [68, 22, 41, 32],
       [ 4, 56, 25,  7],
       [71, 92, 11, 91],
       [51, 88,  7,  8],
       [45, 43, 85, 87]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
# code
a

array([110, 530,  82,  87,  67,   5,  23,  71,  38,  60,  54,  41,  96,
        23,  27])

In [55]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [57]:
# code
a

array([110, 530,  82,  87,  67,   5,  23,  71,  38,  60,  54,  41,  96,
        23,  27])

In [58]:
np.delete(a,[0,2,4])

array([530,  87,   5,  23,  71,  38,  60,  54,  41,  96,  23,  27])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [59]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.intersect1d(m,n)

array([3, 4, 5])

In [61]:
np.setdiff1d(n,m)

array([6, 7])

In [62]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [63]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals